# Producer
input:
  generate:
    mapping: |
      root = {}
    interval: "30s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "RedisLogic"
      hp_redis_cmd:
        profile: |-
          {{json(redis_default)}}
        command: ZRANGEBYSCORE
        args_mapping: root = [ "My_Sorted_Set", "3",  "+inf" ]
        result: root = this
        result_mode: merge
        output: |
          root.values = this

    - label: "OutputData"
      dump_log:

# No output
output:
  label: ""
  drop: {}
