version: '3.6'

networks:
  my_custom_network:
    external: true

services:
  benthos:
    #image: wutichai/hyper-runtime:v8.3.1.4
    #image: wdsregistry1.beebuddy.net:9900/hyper-runtime:v8.3.1.4
    #image: wdsregistry1.beebuddy.net:9900/hyper-runtime:v8.3.1.8
    image: wdsregistry1.beebuddy.net:9900/hyper-runtime:v8.3.1.9
    container_name: benthos
    volumes:
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/localtime:ro
      - ./flows:/data/deployed
      - ./data/csv:/data/csv
      - ./data/output:/data/output
      - ./data/test:/data/test
    environment:
      - MAX_SPARED_THREADS=5
      - LOG_FORMAT=json
      - JSON_USE_NUMBER=false
      - HYPER_NODE_PATH=/data/deployed
    networks:
      - my_custom_network
    ports:
      - "8124:8124"
    
    depends_on:
      - redis



  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - my_custom_network
    # ports:
    #   - "6379:6379" 



