services:
  benthos:
    #image: wutichai/hyper-runtime:v8.3.1.4
    #image: wdsregistry1.beebuddy.net:9900/hyper-runtime:v8.3.1.4
    #image: wdsregistry1.beebuddy.net:9900/hyper-runtime:v8.3.1.8
    #image: wdsregistry1.beebuddy.net:9900/hyper-runtime:v8.3.1.9
    image: wdsregistry1.beebuddy.net:9900/hyper-runtime:v8.3.1.10
    container_name: benthos
    volumes:
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/localtime:ro
      - ./flows:/data/deployed
      - ./data/csv:/data/csv
      - ./data/output:/data/output
      - ./data/test:/data/test
    environment:
      - MAX_SPARED_THREADS=5
      - LOG_FORMAT=json
      - JSON_USE_NUMBER=false
      - HYPER_NODE_PATH=/data/deployed
      #- HYPER_REDIS=redis://host.docker.internal:6379
      - HYPER_REDIS=redis://default:securepassword@host.docker.internal:16379

    ports:
      - "8124:8124"
