
input:
  http_server:
    timeout: 60s
    path: "/megw/apis/stream/{service}/{version}/{action}"
    allowed_verbs:
      - POST
      - GET


pipeline:
  processors:


    # Filter Input
    - label: "FilterInputMainflow"
      hp_transform:
        name: "Filter Input"
        result_mode: new
        mapping: |-
          meta mainFlowId = "1ce814de46f542cf"
          meta flowId = "1ce814de46f542cf"
          meta subflowId = "none"
          meta testId = if meta("X-Trace").or("false") == "true" { if this._hyper_testId != null { this._hyper_testId } else if this.testId != null { this.testId } } else { deleted() }
          meta username = if meta("X-Trace").or("false") == "true" && this._hyper_username != null { this._hyper_username } else { meta("X-Username").or(deleted()) }

          root = this
          
      

    # Node start
    - label: "{package}_44653c324ff5adb0"
      hp_resource:
        id: "{package}_44653c324ff5adb0"
        goto_route:
          success: "this.{package}_995821fbd06eb42a"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "1ce814de46f542cf",
            "nodeId":"44653c324ff5adb0",
            "nodeType":"start"
          }
    

    # Node end
    - label: "{package}_b24edb674d31569e"
      hp_resource:
        id: "{package}_b24edb674d31569e"
        goto_route:
          success: "this.{package}_endnode"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "1ce814de46f542cf",
            "nodeId":"b24edb674d31569e",
            "nodeType":"end"
          }
    

    # Node ssqsubflow
    - label: "{package}_de42af75444ba06e"
      hp_resource:
        id: "{package}_de42af75444ba06e"
        goto_route:
          success: "this.{package}_b24edb674d31569e"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "1ce814de46f542cf",
            "nodeId":"de42af75444ba06e",
            "nodeType":"ssqsubflow"
          }
    

    # Node code
    - label: "{package}_995821fbd06eb42a"
      hp_resource:
        id: "{package}_995821fbd06eb42a"
        goto_route:
          success: "this.{package}_de42af75444ba06e"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "1ce814de46f542cf",
            "nodeId":"995821fbd06eb42a",
            "nodeType":"code"
          }
    
    # Exception resources
    - catch:
      - hp_transform:
          name: "Prepare Exception"
          input: |-
            root = this
          mapping: |-
            let result_status = {"description": error().or(metadata("error_message").or("Exception")), "code": metadata("error_code").or("500") }
            
            meta result_status = $result_status
            meta result_error = true

            root = this

            root._hyper_code = $result_status.code
            root._hyper_message = $result_status.description

          result_mode: merge

      - dump_log:
          payload: true


# 
    # End flow (Standard-Format)
    - label: "{package}_endnode"
      hp_transform:
        name: "Pepare Result"
        mapping: |-
          let result_status = meta("result_status")
          let code = $result_status.code.or("200")
          let description = $result_status.description.or("Success")
          root = this
          
          let del_result_status = meta_delete("result_status")

        result_mode: new
# 
output:
  switch:
    cases:
      - check: meta("input_channel") == "http"
        output:
          sync_response: {}
      - check: meta("input_channel") == "socket_sync"
        output:
          sync_response: {}
      - output:
          drop: {}

