# Producer
input:
  generate:
    mapping: |
      root = {
        "key": "rgls83p54^cap)21c(ak(&_kiho+meztq1b-o(xwbk*!kisruo",
        "data": "5y0m7eeay0+CyvBTzm4qSOyryDwRQ+TvTaB4PT/WI3JSsUw082tJjhpAuMZ7auDO70YOgjixLtP+b2SdwyapXADGgHR/IFbPnEoLrDGNifo="
      }
    interval: "30s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "Test Case 1-1"
      hp_transform:
        name: "hp_transform"
        input: |
            root = this


        mapping: |
            root = {}
            root.decrypted = this.data.gcm_decode(this.key.string(), this.data.string(), -1).or("")

        result_mode: merge  
          

    - label: "OutputData"
      dump_log:

    - label: "Error"
      catch:
        - dump_log:

# No output
output:
  label: ""
  drop: {}
