
input:
  http_server:
    timeout: 60s
    path: "/megw/apis/stream/{service}/{version}/{action}"
    allowed_verbs:
      - POST
      - GET


pipeline:
  processors:


    # Filter Input
    - label: "FilterInputMainflow"
      hp_transform:
        name: "Filter Input"
        result_mode: new
        mapping: |-
          meta mainFlowId = "4bf82fdb553a38fc"
          meta flowId = "4bf82fdb553a38fc"
          meta subflowId = "none"
          meta testId = if meta("X-Trace").or("false") == "true" { if this._hyper_testId != null { this._hyper_testId } else if this.testId != null { this.testId } } else { deleted() }
          meta username = if meta("X-Trace").or("false") == "true" && this._hyper_username != null { this._hyper_username } else { meta("X-Username").or(deleted()) }

          root = this
          
      

    # Node start
    - label: "{package}_3eaff8e24ee876ea"
      hp_resource:
        id: "{package}_3eaff8e24ee876ea"
        goto_route:
          success: "this.{package}_a74b5755b718656d"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4bf82fdb553a38fc",
            "nodeId":"3eaff8e24ee876ea",
            "nodeType":"start"
          }
    

    # Node code
    - label: "{package}_a9789635755201a2"
      hp_resource:
        id: "{package}_a9789635755201a2"
        goto_route:
          success: "this.{package}_c254331f7edd078e"
          failure: "this.{package}_a3b0d4be2b64ed2b"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4bf82fdb553a38fc",
            "nodeId":"a9789635755201a2",
            "nodeType":"code"
          }
    

    # Node end
    - label: "{package}_ce72d9ddef3b6ac4"
      hp_resource:
        id: "{package}_ce72d9ddef3b6ac4"
        goto_route:
          success: "this.{package}_endnode"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4bf82fdb553a38fc",
            "nodeId":"ce72d9ddef3b6ac4",
            "nodeType":"end"
          }
    

    # Node define
    - label: "{package}_a74b5755b718656d"
      hp_resource:
        id: "{package}_a74b5755b718656d"
        goto_route:
          success: "this.{package}_a9789635755201a2"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4bf82fdb553a38fc",
            "nodeId":"a74b5755b718656d",
            "nodeType":"define"
          }
    

    # Node code
    - label: "{package}_c254331f7edd078e"
      hp_resource:
        id: "{package}_c254331f7edd078e"
        goto_route:
          success: "this.{package}_ce72d9ddef3b6ac4"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4bf82fdb553a38fc",
            "nodeId":"c254331f7edd078e",
            "nodeType":"code"
          }
    

    # Node code
    - label: "{package}_a3b0d4be2b64ed2b"
      hp_resource:
        id: "{package}_a3b0d4be2b64ed2b"
        goto_route:
          success: "this.{package}_ce72d9ddef3b6ac4"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4bf82fdb553a38fc",
            "nodeId":"a3b0d4be2b64ed2b",
            "nodeType":"code"
          }
    
    # Exception resources
    - catch:
      - hp_transform:
          name: "Prepare Exception"
          input: |-
            root = this
          mapping: |-
            meta result_status = {"description": error().or(metadata("error_message").or("Exception")), "code": metadata("error_code").or("500") }
            meta result_error = true
          result_mode: merge
          output: |-
            root = this
      - dump_log:
          payload: false


    # End flow (Standard-Format)
    - label: "{package}_endnode"
      hp_transform:
        name: "Pepare Result"
        mapping: |-
          let result_status = meta("result_status")
          let code = $result_status.code.or("200")
          let description = $result_status.description.or("Success")
          root = this
          
          let del_result_status = meta_delete("result_status")

        result_mode: new

output:
  switch:
    cases:
      - check: meta("input_channel") == "http"
        output:
          sync_response: {}
      - check: meta("input_channel") == "socket_sync"
        output:
          sync_response: {}
      - output:
          drop: {}

