# Producer
input:
  generate:
    mapping: |
      root = {
        "A": "A",
        "M": {
          "N": "NN"
        },
        "id_prefix": "X0"
      }
    interval: "30s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "Test Case 1-1"
      hp_transform:
        name: "hp_transform"
        input: |
          root = this
          let timestamp = now()
          root.yy = $timestamp.ts_format("06")
          root.ddd = $timestamp.ts_format("002")
          root.HHmmss = $timestamp.ts_format("150405")
          root.microsec = $timestamp.ts_format(".000000")

        mapping: |
          root = this
          let us = this.microsec.replace(".", "")
          root.ttxid = this.yy+ this.ddd + this.id_prefix + this.HHmmss + $us

        result_mode: new

        output: |
          root = {}
          let needLen = 25 - this.ttxid.length()
          let charRan = generate_random_string(length: $needLen, upper: true, lower: false, number: true, symbol: false)
          root.ttxID = this.ttxid + $charRan
   


    - label: "OutputData"
      dump_log:

# No output
output:
  label: ""
  drop: {}
