
input:
  http_server:
    timeout: 60s
    path: "/megw/apis/stream/{service}/{version}/{action}"
    allowed_verbs:
      - POST
      - GET


pipeline:
  processors:


    # Filter Input
    - label: "FilterInputMainflow"
      hp_transform:
        name: "Filter Input"
        result_mode: new
        mapping: |-
          meta mainFlowId = "cc01d0c3feb5a043"
          meta flowId = "cc01d0c3feb5a043"
          meta subflowId = "none"
          meta testId = if meta("X-Trace").or("false") == "true" { if this._hyper_testId != null { this._hyper_testId } else if this.testId != null { this.testId } } else { deleted() }
          meta username = if meta("X-Trace").or("false") == "true" && this._hyper_username != null { this._hyper_username } else { meta("X-Username").or(deleted()) }

          root = this
          
      

    # Node start
    - label: "{package}_988896bd7cda5e14"
      hp_resource:
        id: "{package}_988896bd7cda5e14"
        goto_route:
          success: "this.{package}_dd27a6868a823c64"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"988896bd7cda5e14",
            "nodeType":"start"
          }
    

    # Node define
    - label: "{package}_dd27a6868a823c64"
      hp_resource:
        id: "{package}_dd27a6868a823c64"
        goto_route:
          success: "this.{package}_877ba5551e8112c5"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"dd27a6868a823c64",
            "nodeType":"define"
          }
    

    # Node end
    - label: "{package}_d8cc3521eb2672b3"
      hp_resource:
        id: "{package}_d8cc3521eb2672b3"
        goto_route:
          success: "this.{package}_endnode"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"d8cc3521eb2672b3",
            "nodeType":"end"
          }
    

    # Node decision
    - label: "{package}_877ba5551e8112c5"
      hp_resource:
        id: "{package}_877ba5551e8112c5"
        goto_route:
          success: '${! metadata("result_route") }'
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"877ba5551e8112c5",
            "nodeType":"decision"
          }
    

    # Node code
    - label: "{package}_72463e1ccd867f45"
      hp_resource:
        id: "{package}_72463e1ccd867f45"
        goto_route:
          success: "this.{package}_6acc56a24935d542"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"72463e1ccd867f45",
            "nodeType":"code"
          }
    

    # Node transform
    - label: "{package}_a877734b3ba058a3"
      hp_resource:
        id: "{package}_a877734b3ba058a3"
        goto_route:
          success: "this.{package}_72463e1ccd867f45"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"a877734b3ba058a3",
            "nodeType":"transform"
          }
    

    # Node transform
    - label: "{package}_669089f861731b54"
      hp_resource:
        id: "{package}_669089f861731b54"
        goto_route:
          success: "this.{package}_1c431492c3958b3c"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"669089f861731b54",
            "nodeType":"transform"
          }
    

    # Node code
    - label: "{package}_634750e121aa2295"
      hp_resource:
        id: "{package}_634750e121aa2295"
        goto_route:
          success: "this.{package}_d8cc3521eb2672b3"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"634750e121aa2295",
            "nodeType":"code"
          }
    

    # Node code
    - label: "{package}_1c431492c3958b3c"
      hp_resource:
        id: "{package}_1c431492c3958b3c"
        goto_route:
          success: "this.{package}_3e5c173d128855b6"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"1c431492c3958b3c",
            "nodeType":"code"
          }
    

    # Node transform
    - label: "{package}_3e5c173d128855b6"
      hp_resource:
        id: "{package}_3e5c173d128855b6"
        goto_route:
          success: "this.{package}_634750e121aa2295"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"3e5c173d128855b6",
            "nodeType":"transform"
          }
    

    # Node end
    - label: "{package}_6acc56a24935d542"
      hp_resource:
        id: "{package}_6acc56a24935d542"
        goto_route:
          success: "this.{package}_endnode"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "cc01d0c3feb5a043",
            "nodeId":"6acc56a24935d542",
            "nodeType":"end"
          }
    
    # Exception resources
    - catch:
      - hp_transform:
          name: "Prepare Exception"
          input: |-
            root = this
          mapping: |-
            meta result_status = {"description": error().or(metadata("error_message").or("Exception")), "code": metadata("error_code").or("500") }
            meta result_error = true
          result_mode: merge
          output: |-
            root = this
      - dump_log:
          payload: false


    # End flow (Standard-Format)
    - label: "{package}_endnode"
      hp_transform:
        name: "Pepare Result"
        mapping: |-
          let result_status = meta("result_status")
          let code = $result_status.code.or("200")
          let description = $result_status.description.or("Success")
          root = this
          root._hyper_code = $code
          root._hyper_message = $description
        result_mode: new

output:
  switch:
    cases:
      - check: meta("input_channel") == "http"
        output:
          sync_response: {}
      - check: meta("input_channel") == "socket_sync"
        output:
          sync_response: {}
      - output:
          drop: {}

