
input:
  http_server:
    timeout: 60s
    path: "/megw/apis/stream/{service}/{version}/{action}"
    allowed_verbs:
      - POST
      - GET


pipeline:
  processors:


    # Filter Input
    - label: "FilterInputMainflow"
      hp_transform:
        name: "Filter Input"
        result_mode: new
        mapping: |-
          meta mainFlowId = "e52ad75f1c8cf5f9"
          meta flowId = "e52ad75f1c8cf5f9"
          meta subflowId = "none"
          meta testId = if meta("X-Trace").or("false") == "true" { if this._hyper_testId != null { this._hyper_testId } else if this.testId != null { this.testId } } else { deleted() }
          meta username = if meta("X-Trace").or("false") == "true" && this._hyper_username != null { this._hyper_username } else { meta("X-Username").or(deleted()) }

          root = this
          
      

    # Node start
    - label: "{package}_2d47d8da6c04e290"
      hp_resource:
        id: "{package}_2d47d8da6c04e290"
        goto_route:
          success: "this.{package}_01ca31bb3b140216"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "e52ad75f1c8cf5f9",
            "nodeId":"2d47d8da6c04e290",
            "nodeType":"start"
          }
    

    # Node define
    - label: "{package}_01ca31bb3b140216"
      hp_resource:
        id: "{package}_01ca31bb3b140216"
        goto_route:
          success: "this.{package}_6a546dacdda16f7e"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "e52ad75f1c8cf5f9",
            "nodeId":"01ca31bb3b140216",
            "nodeType":"define"
          }
    

    # Node code
    - label: "{package}_6a546dacdda16f7e"
      hp_resource:
        id: "{package}_6a546dacdda16f7e"
        goto_route:
          success: "this.{package}_36417c67a049a5e3"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "e52ad75f1c8cf5f9",
            "nodeId":"6a546dacdda16f7e",
            "nodeType":"code"
          }
    

    # Node ssqsubflow
    - label: "{package}_36417c67a049a5e3"
      hp_resource:
        id: "{package}_36417c67a049a5e3"
        goto_route:
          success: "this.{package}_73566aedae238f08"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "e52ad75f1c8cf5f9",
            "nodeId":"36417c67a049a5e3",
            "nodeType":"ssqsubflow"
          }
    

    # Node transform
    - label: "{package}_73566aedae238f08"
      hp_resource:
        id: "{package}_73566aedae238f08"
        goto_route:
          success: "this.{package}_6292d3a5ce1b5d68"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "e52ad75f1c8cf5f9",
            "nodeId":"73566aedae238f08",
            "nodeType":"transform"
          }
    

    # Node end
    - label: "{package}_6292d3a5ce1b5d68"
      hp_resource:
        id: "{package}_6292d3a5ce1b5d68"
        goto_route:
          success: "this.{package}_endnode"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "e52ad75f1c8cf5f9",
            "nodeId":"6292d3a5ce1b5d68",
            "nodeType":"end"
          }
    
    # Exception resources
    - catch:
      - hp_transform:
          name: "Prepare Exception"
          input: |-
            root = this
          mapping: |-
            meta result_status = {"description": error().or(metadata("error_message").or("Exception")), "code": metadata("error_code").or("500") }
            meta result_error = true
          result_mode: merge
          output: |-
            root = this
      - dump_log:
          payload: false


    # End flow (Standard-Format)
    - label: "{package}_endnode"
      hp_transform:
        name: "Pepare Result"
        mapping: |-
          let result_status = meta("result_status")
          let code = $result_status.code.or("200")
          let description = $result_status.description.or("Success")
          root = this
          root._hyper_code = $code
          root._hyper_message = $description
        result_mode: new

output:
  switch:
    cases:
      - check: meta("input_channel") == "http"
        output:
          sync_response: {}
      - check: meta("input_channel") == "socket_sync"
        output:
          sync_response: {}
      - output:
          drop: {}

