# Producer
input:
  generate:
    mapping: |
      root = {
        "A": "A"
      }
    interval: "30s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "LogData"
      log:
        level: "INFO"
        message: "${! content()}"

    - label: "OutputData"
      dump_log:

# No output
output:
  label: ""
  drop: {}
