version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network

  redis2:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis2_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network

volumes:
  redis_data:
  redis2_data:

networks:
  redis_network:
    driver: bridge