
input:
  http_server:
    timeout: 60s
    path: "/megw/apis/stream/{service}/{version}/{action}"
    allowed_verbs:
      - POST
      - GET


pipeline:
  processors:


    # Filter Input
    - label: "FilterInputMainflow"
      hp_transform:
        name: "Filter Input"
        result_mode: new
        mapping: |-
          meta mainFlowId = "2040740a710a3b74"
          meta flowId = "2040740a710a3b74"
          meta subflowId = "none"
          meta testId = if meta("X-Trace").or("false") == "true" { if this._hyper_testId != null { this._hyper_testId } else if this.testId != null { this.testId } } else { deleted() }
          meta username = if meta("X-Trace").or("false") == "true" && this._hyper_username != null { this._hyper_username } else { meta("X-Username").or(deleted()) }

          root = this
          
      

    # Node start
    - label: "{package}_92ac0d4ae5ba01db"
      hp_resource:
        id: "{package}_92ac0d4ae5ba01db"
        goto_route:
          success: "this.{package}_1f49250780f1263b"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "2040740a710a3b74",
            "nodeId":"92ac0d4ae5ba01db",
            "nodeType":"start"
          }
    

    # Node define
    - label: "{package}_1f49250780f1263b"
      hp_resource:
        id: "{package}_1f49250780f1263b"
        goto_route:
          success: "this.{package}_aae0b7b2e75c7f92"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "2040740a710a3b74",
            "nodeId":"1f49250780f1263b",
            "nodeType":"define"
          }
    

    # Node code
    - label: "{package}_7b4d4e0e427c4c60"
      hp_resource:
        id: "{package}_7b4d4e0e427c4c60"
        goto_route:
          success: "this.{package}_160128c86a737f0e"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "2040740a710a3b74",
            "nodeId":"7b4d4e0e427c4c60",
            "nodeType":"code"
          }
    

    # Node end
    - label: "{package}_4f368651b593cc94"
      hp_resource:
        id: "{package}_4f368651b593cc94"
        goto_route:
          success: "this.{package}_endnode"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "2040740a710a3b74",
            "nodeId":"4f368651b593cc94",
            "nodeType":"end"
          }
    

    # Node code
    - label: "{package}_b3b8663b2548a369"
      hp_resource:
        id: "{package}_b3b8663b2548a369"
        goto_route:
          success: "this.{package}_7b4d4e0e427c4c60"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "2040740a710a3b74",
            "nodeId":"b3b8663b2548a369",
            "nodeType":"code"
          }
    

    # Node decision
    - label: "{package}_aae0b7b2e75c7f92"
      hp_resource:
        id: "{package}_aae0b7b2e75c7f92"
        goto_route:
          success: '${! metadata("result_route") }'
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "2040740a710a3b74",
            "nodeId":"aae0b7b2e75c7f92",
            "nodeType":"decision"
          }
    

    # Node code
    - label: "{package}_160128c86a737f0e"
      hp_resource:
        id: "{package}_160128c86a737f0e"
        goto_route:
          success: "this.{package}_aae0b7b2e75c7f92"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "2040740a710a3b74",
            "nodeId":"160128c86a737f0e",
            "nodeType":"code"
          }
    
    # Exception resources
    - catch:
      - hp_transform:
          name: "Prepare Exception"
          input: |-
            root = this
          mapping: |-
            let result_status = {"description": error().or(metadata("error_message").or("Exception")), "code": metadata("error_code").or("500") }
            
            meta result_status = $result_status
            meta result_error = true

            root = this

            root._hyper_code = $result_status.code
            root._hyper_message = $result_status.description

          result_mode: merge

      - dump_log:
          payload: true



    # End flow (Standard-Format)
    - label: "{package}_endnode"
      hp_transform:
        name: "Pepare Result"
        mapping: |-
          let result_status = meta("result_status")
          let code = $result_status.code.or("200")
          let description = $result_status.description.or("Success")
          root = this
          
          let del_result_status = meta_delete("result_status")

        result_mode: new

output:
  switch:
    cases:
      - check: meta("input_channel") == "http"
        output:
          sync_response: {}
      - check: meta("input_channel") == "socket_sync"
        output:
          sync_response: {}
      - output:
          drop: {}

