# Producer
input:
  generate:
    mapping: |
      root = {
        "A": "A"
      }
    interval: "30s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "TimeDelay"
      sleep:
        duration: "10s"

    - label: "OutputData"
      dump_log:

# No output
output:
  label: ""
  drop: {}
