# Producer
input:
  generate:
    mapping: |
      root = {
        "A": "A"
      }
    interval: "20s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "my_resource"
      hp_resource:
        id: "my_resource"
        goto_route:
          success: "this.OutputData"
          #failure: "this.ErrorData"

    - label: "OutputData"
      dump_log:

    - catch:
        - label: "ErrorData"
          dump_log:

# No output
output:
  label: ""
  drop: {}
