# Producer
input:
  generate:
    mapping: |
      root = {
        "A": "A",
        "M": {
          "N": "NN"
        },
        "frequency": {
           "dateStart": "2025-03-01"
        }
      }
    interval: "30s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "Test Case 1-1"
      hp_transform:
        name: "hp_transform"
        input: |
          root = this
          root.B = "B"

        mapping: |
          root = this

        result_mode: merge

        output: |
          root = {}
          root.next_month = this.frequency.dateStart.ts_next_month("2006-01-02", "Asia/Bangkok", 1)

    - label: "OutputData"
      dump_log:

# No output
output:
  label: ""
  drop: {}
