input:
  csv:
    paths:
      - /data/csv/foo.csv
      #- /data/csv/bar.csv
      #- /data/csv/cities.csv
    parse_header_row: true

pipeline:
  processors:
    - log:
        level: INFO
        message: "*****************************"
    - dump_log:

output:
