# Producer
input:
  generate:
    mapping: |
      root = {
        "A": "A",
         "trans": {
            "debtor": {
                "Account": "1234567890",
                "AccountName": "John Doe"
            }
        }
      }
    interval: "30s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "Test Case 1-1"
      hp_transform:
        name: "hp_transform"
        input: |
          root = this

        mapping: |
          root = {}
          root.trans = {}
          root.trans.debtor = {}
          root.trans.debtor =  {
                      "AccountId": this.trans.debtor.Account.int64()
                  }

        result_mode: merge

        output: |
          root = this
          

    - label: "OutputData"
      dump_log:

# No output
output:
  label: ""
  drop: {}
