# Common config fields, showing default values
input:
  label: "MyLabel"
  http_server:
    path: /test
    allowed_verbs:
      - POST
      - GET
    timeout: 5s

pipeline:
  processors:
    - mapping: |-
        root = this
        root.name = "Adirak"
        root.id = "32145456545"

output:
  sync_response: {}
