# Producer
input:
  generate:
    mapping: |
      root = {
        "A": "A",
        "result": {
          "customerID": 310001462,
          "restriction_cif": [
            { "exdt": "20211011", "rflg": "11"},
            { "exdt": "20211011", "rflg": "13"}
          ]
        },
        "result2": {
          "999999999": "11"
        }
      }
    interval: "20s"

pipeline:
  processors:
    - try:
        - label: "InputData"
          dump_log:

        - label: "Test Case 1-2"
          hp_transform:
            name: "hp_transform"
            input: |
              root = this

            mapping: |
              root = this
              let cur_date = "20211011".number()
              let acn = this.result.customerID.string()
              
              let restTmp = this.result.restriction_cif.map_each(item -> if item.rflg == "11" && item.exdt.number() >= $cur_date {
                item
              } else {
                deleted()
              })

              root.rest = if $restTmp.length().or(0) > 0 {
                  {$acn : $restTmp.index(0).rflg}
                } else {
                  {}
                }

            output: |
              root = {}
              root.rest = this.rest.merge(this.result2)
          
            result_mode: "new"


        - label: "OutputData"
          dump_log:

    - catch:
        - label: "ErrorData"
          dump_log:

# No output
output:
  label: ""
  drop: {}
