cache_plugins:
  - label: _default_cache
    redis:
      url: redis://redis:6379
      kind: simple
      master: ""
      prefix: "hp_cache_"
      retries:
        initial_interval: 500ms
        max_interval: 1s
        max_elapsed_time: 5s
