# Producer
input:
  generate:
    mapping: |
      root = {
        "A": "A",
        "to": ["adirak@gmail.com"],
        "cc": ["adirak@techberry.co.th"],
        "body": "body test send mail"
      }
    interval: "300s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "Test Send Mail"
      sendmail:
        name: sendmail
        host: "smtp.techberry.co.th"
        tls: false
        port: 587
        connect_timeout: 10
        send_timeout: 10
        username: "testhyper@techberry.co.th"
        password: "Sa20vpKw"
        from: "testhyper@techberry.co.th"
        to: ["adirak@gmail.com"]
        bcc: ["adirak@techberry.co.th"]
        mime: "text/html"
        subject: "Test Send Mail"
        body: "test send mail"
        output: |-
          root = {}
          root.sendmail = "sent"
        result_mode: merge

    - label: "OutputData"
      dump_log:

# No output
output:
  label: ""
  drop: {}
