# Producer
input:
  generate:
    mapping: |
      root = {
        "num":"0321158431",
        "num2":"0123456789.05",

      }
    interval: "30s"

pipeline:
  processors:
    - label: "InputData"
      dump_log:

    - label: "Test Case 1-1"
      hp_transform:
        name: "hp_transform"
        input: |
          root = this

        mapping: |
          root = {}
          root.numInt = this.num.int().or(0)
          root.numInt2 = this.num2.number(0).ceil()
          root.strNum2 = this.num2.number(0).ceil().string()

        result_mode: new

    - label: "OutputData"
      dump_log:

# No output
output:
  label: ""
  drop: {}
