# Consumer fanout 2
input:
  label: "ConsumerFanout2"
  amqp_0_9:
    urls: 
      - amqp://guest:guest@host.docker.internal:5672/
    queue: "line_queue"
    queue_declare:
      enabled: true
      durable: true
    bindings_declare:
      - exchange: "test.fanout.noti"
        key: ""                  # ไม่จำเป็นต้องใส่ routing key
    prefetch_count: 100

pipeline:
  processors:
    - dump_log:
    - sleep:
        duration: 1s


# Config fields, showing default values
output:
  label: ""
  drop: {}