
input:
  http_server:
    timeout: 60s
    path: "/megw/apis/stream/{service}/{version}/{action}"
    allowed_verbs:
      - POST
      - GET


pipeline:
  processors:


    # Filter Input
    - label: "FilterInputMainflow"
      hp_transform:
        name: "Filter Input"
        result_mode: new
        mapping: |-
          meta mainFlowId = "4f9cdf83e9ef7f69"
          meta flowId = "4f9cdf83e9ef7f69"
          meta subflowId = "none"
          meta testId = if meta("X-Trace").or("false") == "true" { if this._hyper_testId != null { this._hyper_testId } else if this.testId != null { this.testId } } else { deleted() }
          meta username = if meta("X-Trace").or("false") == "true" && this._hyper_username != null { this._hyper_username } else { meta("X-Username").or(deleted()) }

          root = this
          
      

    # Node start
    - label: "{package}_718101733002fe26"
      hp_resource:
        id: "{package}_718101733002fe26"
        goto_route:
          success: "this.{package}_825d5b87704fa76d"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4f9cdf83e9ef7f69",
            "nodeId":"718101733002fe26",
            "nodeType":"start"
          }
    

    # Node define
    - label: "{package}_825d5b87704fa76d"
      hp_resource:
        id: "{package}_825d5b87704fa76d"
        goto_route:
          success: "this.{package}_610d909d80459262"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4f9cdf83e9ef7f69",
            "nodeId":"825d5b87704fa76d",
            "nodeType":"define"
          }
    

    # Node decision
    - label: "{package}_610d909d80459262"
      hp_resource:
        id: "{package}_610d909d80459262"
        goto_route:
          success: '${! metadata("result_route") }'
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4f9cdf83e9ef7f69",
            "nodeId":"610d909d80459262",
            "nodeType":"decision"
          }
    

    # Node exception
    - label: "{package}_38ef8513ac2d8fbf"
      hp_resource:
        id: "{package}_38ef8513ac2d8fbf"
        goto_route:
          success: "this.{package}_endnode"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4f9cdf83e9ef7f69",
            "nodeId":"38ef8513ac2d8fbf",
            "nodeType":"exception"
          }
    

    # Node end
    - label: "{package}_0eedfd57114d387c"
      hp_resource:
        id: "{package}_0eedfd57114d387c"
        goto_route:
          success: "this.{package}_endnode"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4f9cdf83e9ef7f69",
            "nodeId":"0eedfd57114d387c",
            "nodeType":"end"
          }
    

    # Node ssqsubflow
    - label: "{package}_5b4074b863974872"
      hp_resource:
        id: "{package}_5b4074b863974872"
        goto_route:
          success: "this.{package}_05361017d9070d29"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4f9cdf83e9ef7f69",
            "nodeId":"5b4074b863974872",
            "nodeType":"ssqsubflow"
          }
    

    # Node code
    - label: "{package}_05361017d9070d29"
      hp_resource:
        id: "{package}_05361017d9070d29"
        goto_route:
          success: "this.{package}_0eedfd57114d387c"
          #failure: "this.{package}_exception"
          
        metadata: |-
          {
            "scopeType": "mainFlow",
            "scopeId": "4f9cdf83e9ef7f69",
            "nodeId":"05361017d9070d29",
            "nodeType":"code"
          }
    
    # Exception resources
    - catch:
      - hp_transform:
          name: "Prepare Exception"
          input: |-
            root = this
          mapping: |-
            let result_status = {"description": error().or(metadata("error_message").or("Exception")), "code": metadata("error_code").or("500") }
            
            meta result_status = $result_status
            meta result_error = true

            root = this

            root._hyper_code = $result_status.code
            root._hyper_message = $result_status.description

          result_mode: merge

      - dump_log:
          payload: true



    # End flow (Standard-Format)
    - label: "{package}_endnode"
      hp_transform:
        name: "Pepare Result"
        mapping: |-
          let result_status = meta("result_status")
          let code = $result_status.code.or("200")
          let description = $result_status.description.or("Success")
          root = this
          
          let del_result_status = meta_delete("result_status")

        result_mode: new

output:
  switch:
    cases:
      - check: meta("input_channel") == "http"
        output:
          sync_response: {}
      - check: meta("input_channel") == "socket_sync"
        output:
          sync_response: {}
      - output:
          drop: {}

